/**
 
opcode   type   RegWrite ALUSrcA ALUSrcB MemRead MemWrite MemtoReg Branch Jump ALUOp ImmSel
1101111  jal    1        00      0       0       0        10       0      01   00    100
1100111  jalr   1        00      1       0       0        10       0      10   00    000
 **/
module control (
    input  logic [6:0] opcode,
    output logic       reg_write,
    output logic [1:0] alu_src_a,
    output logic       alu_src_b,
    output logic       mem_read,
    output logic       mem_write,
    output logic [1:0] MemtoReg,
    output logic       branch,
    output logic [1:0] jump,
    output logic [1:0] alu_op,
    output logic [2:0] imm_sel
);
    localparam logic [6:0] R_TYPE = 7'b0110011;
    localparam logic [6:0] LOAD   = 7'b0000011;
    localparam logic [6:0] STORE  = 7'b0100011;
    localparam logic [6:0] BRANCH = 7'b1100011;
    localparam logic [6:0] I_TYPE = 7'b0010011;
    localparam logic [6:0] LUI    = 7'b0110111;
    localparam logic [6:0] AUIPC  = 7'b0010111;
    localparam logic [6:0] JAL    = 7'b1101111;
    localparam logic [6:0] JALR   = 7'b1100111;

    always_comb begin
        // Defaults represent an illegal instruction/NOP and prevent combinational latches.
        reg_write = 1'b0;
        alu_src_a = 2'b00;
        alu_src_b = 1'b0;
        mem_read  = 1'b0;
        mem_write = 1'b0;
        MemtoReg  = 2'b00;
        branch    = 1'b0;
        jump      = 2'b00;
        alu_op    = 2'b00;
        imm_sel   = 3'b000;

        case (opcode)
            R_TYPE: begin //R-type
                reg_write = 1'b1;
                alu_op    = 2'b10;
            end
            LOAD: begin // LB/LH/LW/LBU/LHU
                reg_write = 1'b1;
                alu_src_b = 1'b1;
                mem_read  = 1'b1;
                MemtoReg  = 2'b01;
                imm_sel   = 3'b000;
            end
            STORE: begin // SB/SH/SW
                alu_src_b = 1'b1;
                mem_write = 1'b1;
                imm_sel   = 3'b001;
            end
            BRANCH: begin // Branch result is generated by branch_unit
                branch    = 1'b1;
                alu_op    = 2'b01;
                imm_sel   = 3'b010;
            end
            I_TYPE: begin // ADDI, immediate shifts, logic, and comparisons
                reg_write = 1'b1;
                alu_src_b = 1'b1;
                alu_op    = 2'b11;
                imm_sel   = 3'b000;
            end
            LUI: begin // 0 + U-type immediate
                reg_write = 1'b1;
                alu_src_a = 2'b10;
                alu_src_b = 1'b1;
                imm_sel   = 3'b011;
            end
            AUIPC: begin // PC + U-type immediate
                reg_write = 1'b1;
                alu_src_a = 2'b01;
                alu_src_b = 1'b1;
                imm_sel   = 3'b011;
            end
            JAL: begin // Write back PC+4 and jump to PC+J-imm
                reg_write = 1'b1;
                MemtoReg  = 2'b10;
                jump      = 2'b01;
                imm_sel   = 3'b100;
            end
            JALR: begin // Write back PC+4 and jump to (rs1+I-imm)&~1
                reg_write = 1'b1;
                alu_src_b = 1'b1;
                MemtoReg  = 2'b10;
                jump      = 2'b10;
                imm_sel   = 3'b000;
            end
            default: ;
        endcase
    end
endmodule

module alu_decoder (
    input  logic [1:0] alu_op,
    input  logic [2:0] funct3,
    input  logic       funct7_5,
    output logic [3:0] alu_control
);
    always_comb begin
        // LOAD/STORE/LUI/AUIPC do not depend on funct3/funct7_5 and use addition.
        case (alu_op)
            2'b00: alu_control = 4'b0000; // Address or immediate addition
            2'b01: alu_control = 4'b0001; // Original BEQ subtraction path; branch_unit makes the decision
            2'b10: begin    // R-type
                case (funct3)
                    3'b000: alu_control = funct7_5 ? 4'b0001 : 4'b0000; // SUB/ADD
                    3'b001: alu_control = 4'b0111; // SLL
                    3'b010: alu_control = 4'b0100; // SLT
                    3'b011: alu_control = 4'b0101; // SLTU
                    3'b100: alu_control = 4'b0110; // XOR
                    3'b101: alu_control = funct7_5 ? 4'b1001 : 4'b1000; // SRA/SRL
                    3'b110: alu_control = 4'b0011; // OR
                    3'b111: alu_control = 4'b0010; // AND
                    default: alu_control = 4'b0000;
                endcase
            end
            // For I-type instructions, the top-level MUX already selects imm as b.
            2'b11: begin
                case (funct3)
                    3'b000: alu_control = 4'b0000; // ADDI
                    3'b001: alu_control = 4'b0111; // SLLI
                    3'b010: alu_control = 4'b0100; // SLTI
                    3'b011: alu_control = 4'b0101; // SLTIU
                    3'b100: alu_control = 4'b0110; // XORI
                    3'b101: alu_control = funct7_5 ? 4'b1001 : 4'b1000; // SRAI/SRLI
                    3'b110: alu_control = 4'b0011; // ORI
                    3'b111: alu_control = 4'b0010; // ANDI
                    default: alu_control = 4'b0000;
                endcase
            end
            default: alu_control = 4'b0000;
        endcase
    end
endmodule

module ctrl (
    input  logic [6:0] opcode,
    input  logic [2:0] funct3,
    input  logic       funct7_5,
    output logic       reg_write,
    output logic [1:0] alu_src_a,
    output logic       alu_src_b,
    output logic       mem_read,
    output logic       mem_write,
    output logic [1:0] MemtoReg,
    output logic       branch,
    output logic [1:0] jump,
    output logic [2:0] imm_sel,
    output logic [3:0] alu_control
);
    // alu_op is used only between the main decoder and the ALU decoder.
    logic [1:0] alu_op;

    control u_control (
        .opcode(opcode), .reg_write(reg_write), .alu_src_b(alu_src_b),
        .alu_src_a(alu_src_a), .mem_read(mem_read), .mem_write(mem_write),
        .MemtoReg(MemtoReg), .branch(branch), .jump(jump), .alu_op(alu_op),
        .imm_sel(imm_sel)
    );

    alu_decoder u_alu_decoder (
        .alu_op(alu_op), .funct3(funct3), .funct7_5(funct7_5),
        .alu_control(alu_control)
    );

endmodule
